language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-19.0.0

    # The SDK version used to compile your project
    - android-19
    - sys-img-armeabi-v7a-android-19

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
