language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-21.0.2

    # The SDK version used to compile your project
    - android-20
    - sys-img-armeabi-v7a-android-20

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-20

before_script:
  - echo no | android create avd --force -n test -t android-20 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
